services:
  db:
    container_name: traker_db
    image: postgres:latest
    environment:
      - 'POSTGRES_USER=${POSTGRES_USER:-postgres}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}'
      - 'POSTGRES_DB=${POSTGRES_DB:-traker}'
    ports:
      - "${DB_PORT:-5429}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    container_name: traker_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT:-9090}:8080"
    environment:
      - 'DATABASE_URL=${DATABASE_URL:-db}'
      - 'DATABASE_PORT=${DATABASE_PORT:-5429}'
      - 'DATABASE_NAME=${DATABASE_NAME:-traker}'
      - 'DATABASE_USERNAME=${DATABASE_USERNAME:-postgres}'
      - 'DATABASE_PASSWORD=${DATABASE_PASSWORD:-postgres}'
    depends_on:
      - db

volumes:
  db_data:
